global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'taask'

    static_configs:
    - targets: ['taask-server.taask.svc.cluster.local:3689']

  - job_name: 'linkerd'
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names: ['linkerd']

    relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_container_name
      action: keep
      regex: ^prometheus$

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="linkerd-proxy"}'
        - '{job="linkerd-controller"}'

