{
 "title": "Taask",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(taask_tasks_retrying{})" },
    { "expr": "sum(taask_tasks_active{})" },
    { "expr": "sum(taask_tasks_waiting{})" },
    { "expr": "sum(taask_tasks_queued{})" },
    { "expr": "sum(taask_tasks_running{})" }
   ]
  },
  {
   "title": "Tasks per runner",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(taask_tasks_running) by (runner)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(go_goroutines)" },
    { "expr": "sum(go_threads)" }
   ]
  }
 ]
}